"""empty message

Revision ID: 04722e5b11a9
Revises: 
Create Date: 2025-07-28 09:25:58.233901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04722e5b11a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('total_offers', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_fetched_at'), 'runs', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_runs_id'), 'runs', ['id'], unique=False)
    op.add_column('offers', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers', 'runs', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'run_id')
    op.drop_index(op.f('ix_runs_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_fetched_at'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
