"""Create API-specific tables for User, APIKey, and Run

Revision ID: 6b76fb92ed62
Revises: 
Create Date: 2025-12-05 17:51:30.123456 

"""
from typing import Sequence, Union
import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b76fb92ed62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create 'users' table
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True, index=True, autoincrement=True),
        sa.Column('username', sa.String(), unique=True, index=True, nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), default=True),
    )
    # Create 'api_keys' table
    op.create_table('api_keys',
        sa.Column('id', sa.Integer(), primary_key=True, index=True, autoincrement=True),
        sa.Column('prefix', sa.String(), unique=True, index=True, nullable=False),
        sa.Column('hashed_key', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(), default=sa.func.now()),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('name', sa.String(), nullable=True),
    )
    # Create 'runs' table
    op.create_table('runs',
        sa.Column('id', sa.Integer(), primary_key=True, index=True, autoincrement=True),
        sa.Column('exchange', sa.String(), nullable=False),
        sa.Column('fetched_at', sa.DateTime(), default=sa.func.now(), index=True),
        sa.Column('total_offers', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('api_keys')
    op.drop_table('users')
    # ### end Alembic commands ###